version: '3'
services:
  steamcmd:
    image: czy0612/palworld-server:test
    ports:
      - "2111:8211/udp"
      - "2111:8211"
    volumes:
      - "./data:/home/steam/Steam/steamapps/common/PalServer"
